[unstable]
build-std = ["alloc", "core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-none"
rustflags = ["-C", "force-frame-pointers", "-C", "linker-flavor=gcc"]
